### ISSUE TITLE
install fails 

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/udisks2#1]
@KarstenHopp 

Problem 1: package udisks2-lvm2-2.7.3-1.module_f098a5ee.x86_64 requires lvm2, but none of the providers can be installed  - conflicting requests  - nothing provides device-mapper-persistent-data >= 0.7.0-0.1.rc6 needed by lvm2-2.02.174-2.module_1d780a7b.x86_64

Problem 2: package udisks2-2.7.3-1.module_f098a5ee.x86_64 requires libblockdev-mdraid >= 2.10, but none of the providers can be installed  - conflicting requests  - nothing provides libbytesize.so.1()(64bit) needed by libblockdev-mdraid-2.11-1.module_04d473e8.x86_64

Problem 3: package udisks2-zram-2.7.3-1.module_f098a5ee.x86_64 requires libblockdev-kbd >= 2.10, but none of the providers can be installed  - conflicting requests  - nothing provides bcache-tools >= 1.0.8 needed by libblockdev-kbd-2.11-1.module_04d473e8.x86_64

Problem 4: package udisks2-bcache-2.7.3-1.module_f098a5ee.x86_64 requires libblockdev-kbd >= 2.10, but none of the providers can be installed  - conflicting requests  - nothing provides bcache-tools >= 1.0.8 needed by libblockdev-kbd-2.11-1.module_04d473e8.x86_64

Problem 5: package udisks2-btrfs-2.7.3-1.module_f098a5ee.x86_64 requires libblockdev-btrfs >= 2.10, but none of the providers can be installedn  - conflicting requests  - nothing provides libbytesize.so.1()(64bit) needed by libblockdev-btrfs-2.11-1.module_04d473e8.x86_64

Problem 6: package udisks2-lsm-2.7.3-1.module_f098a5ee.x86_64 requires udisks2(x86-64) = 2.7.3-1.module_f098a5ee, but none of the providers can be installed  - package udisks2-2.7.3-1.module_f098a5ee.x86_64 requires libblockdev-mdraid >= 2.10, but none of the providers can be installed  - conflicting requests  - nothing provides libbytesize.so.1()(64bit) needed by libblockdev-mdraid-2.11-1.module_04d473e8.x86_64

Problem 7: package udisks2-iscsi-2.7.3-1.module_f098a5ee.x86_64 requires udisks2(x86-64) = 2.7.3-1.module_f098a5ee, but none of the providers can be installed  - package udisks2-2.7.3-1.module_f098a5ee.x86_64 requires libblockdev-mdraid >= 2.10, but none of the providers can be installed  - conflicting requests  - nothing provides libbytesize.so.1()(64bit) needed by libblockdev-mdraid-2.11-1.module_04d473e8.x86_64

**Comment by KarstenHopp** [comment]
problems 2-7 need to be fixed in platform, see 
https://github.com/fedora-modularity/baseruntime-package-lists/issues/38
@contyk ^

**Comment by alexxa** [comment]
udisk installs fine in Fedora-Modular-27-20171106.n.0. Closing.

[1] https://ci.centos.org/job/fedora-qa-compose-tests/134/artifact/compose-tests/mod_install_results.log
